configs:
  # provider 0:阿里云 1:腾讯云 2:华为云 3:亚马逊云
  - provider: 0
    name: "阿里云测试账号"
    accessid: "LTAI5tCMzGAatLjwpSLBkbPx"
    accesssecret: "mh6boRgluf7UaCcxbHsUx5WpdQPxAI"
  - provider: 0
    name: "阿里云测试账号2"
    accessid: "LTAI5tJmqtVwbLPyxbYQ42s7"
    accesssecret: "7pZSbzoTykKYQZCzPhBFRfJa8LdTgO"
  - provider: 1
    name: "腾讯云测试账号"
    accessid: "AKID8oIZdZmwLiIemcq2g6QxmLehZFl2qHXW"
    accesssecret: "rGVeYnoZ2F0XpLhplQsgFYcx4uVxKWSA"
  - provider: 1
    name: "腾讯云测试账号2"
    accessid: "AKIDaw0g6EsgYNuBAtuVOmvoPpVv4wXrNeC7"
    accesssecret: "pNdb7OTTIsBCENHuFISMegRloLauye3W"
  - provider: 2
    name: "华为云测试账号"
    accessid: "AVLMF9TWJHR9V5VI3T4S"
    accesssecret: "uxFvapMjzcXjRW8mQqMlNtusMwmMrJmuHmB9I4lr"
  - provider: 3
    name: "亚马逊云测试账号"
    accessid: "AKIAUTN2NJFZUZOG3EFS"
    accesssecret: "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"
